version: '3.8'

services:
  frontend-web:
    image: nginx:alpine
    ports:
      - "8081:80"
    networks:
      - app-network

  backend-cache:
    image: redis:alpine
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
